version: '3'

services:

  # Postgresql DB
  db:
    image: timescale/timescaledb:latest-pg14
    command: -c work_mem=256MB
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      # Postgresql
      - "5432"

  # Elastic
  es:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200
