name: Publish

on:
  pull_request:
    branches: '*'
  push:
    branches: '*'

jobs:
  publish:
    name: "Build and publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Install Python"
        uses: cerc-io/setup-python@v4
        with:
          python-version: '3.8'
      - name: "Print Python version"
        run: python3 --version
      - name: "Install shiv"
        run: pip install shiv
      - name: "Create release"
        uses: cerc-io/action-gh-release@gitea-v1
        # We haven't decided how to trigger this release job.
        # It might be done on creation of a git tag
        # Or it might be done on merge to a release branch
        # Somehow by this point however we need to know the release version
        with:
          tag_name: "v1.2.5"
      - name: "Build local shiv package"
        id: build
        # Build has to be done after deciding on the version because
        # we bundle the version into the build
        run: |
          ./scripts/build_shiv_package.sh
          result_code=$?
          echo "::set-output name=package-file::$(ls ./package/*)"
          exit $result_code          
      - name: "Stage artifact file"
        run: |
                    cp ${{ steps.build.outputs.package-file }} ./laconic-so
      - name: "Upload release artifact"
        uses: cerc-io/action-gh-release@gitea-v1
        with:
          tag_name: "v1.2.5"
          files: ./laconic-so
