# TODO: figure out if this is needed -- it doesn't seem to make sense in the context of the
# current version of vulcanize/ipld-eth-db/Dockerfile, which is only the migrations code, not the DB itself
# The sibling component docker-compose-db-sharding.yml looks more plausible
version: "3.2"
services:
  ipld-eth-db:
    restart: always
    image: vulcanize/ipld-eth-db:local
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_testing"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "5432"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "127.0.0.1:8077:5432"
    command: ["postgres", "-c", "log_statement=all"]